"use client";

import { useState } from "react";

const reasons = [["incapacidad", "Incapacidad"], ["comision_institucional", "Comisión institucional"], ["permiso_staff", "Permiso de staff"], ["fuerza_mayor", "Fuerza mayor"], ["otro", "Otro"]] as const;

export function StaffAttendanceExemptionDialog({ departmentId, employeeId, employeeName, defaultDate }: { departmentId: number; employeeId: number; employeeName: string; defaultDate: string }) {
  const [open, setOpen] = useState(false); const [startDate, setStartDate] = useState(defaultDate); const [endDate, setEndDate] = useState(defaultDate); const [entry, setEntry] = useState(true); const [exit, setExit] = useState(false); const [reason, setReason] = useState("permiso_staff"); const [note, setNote] = useState(""); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); setMessage(null); try { const response = await fetch("/api/staff/attendance-exemptions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ department_id: departmentId, employee_id: employeeId, start_date: startDate, end_date: endDate, exempt_entry: entry, exempt_exit: exit, reason, note: note || null }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail ?? "No fue posible registrar la exención."); setMessage(`${data.length} día(s) justificado(s).`); window.setTimeout(() => window.location.reload(), 600); } catch (error) { setMessage(error instanceof Error ? error.message : "No fue posible registrar la exención."); } finally { setSaving(false); } };
  return <><button type="button" className="secondary-button px-3 py-2 text-xs" onClick={() => setOpen(true)}>Exentar checada</button>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-3" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-3xl bg-white p-5 shadow-2xl"><p className="section-eyebrow">Exención personal</p><h2 className="mt-1 text-lg font-semibold text-(--color-brand-strong)">{employeeName}</h2><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs font-semibold">Desde<input type="date" className="field-input mt-1 w-full" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><label className="text-xs font-semibold">Hasta<input type="date" className="field-input mt-1 w-full" value={endDate} onChange={(event) => setEndDate(event.target.value)} /></label></div><div className="mt-4 flex gap-4 text-sm"><label><input type="checkbox" checked={entry} onChange={(event) => setEntry(event.target.checked)} /> Exentar entrada</label><label><input type="checkbox" checked={exit} onChange={(event) => setExit(event.target.checked)} /> Exentar salida</label></div><label className="mt-4 block text-xs font-semibold">Motivo<select className="field-input mt-1 w-full" value={reason} onChange={(event) => setReason(event.target.value)}>{reasons.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="mt-3 block text-xs font-semibold">Nota{reason === "otro" ? " (obligatoria)" : ""}<textarea className="field-input mt-1 min-h-20 w-full" value={note} onChange={(event) => setNote(event.target.value)} /></label>{message ? <p className="mt-3 text-sm text-(--muted)">{message}</p> : null}<div className="mt-5 flex justify-end gap-2"><button type="button" className="secondary-button px-3 py-2 text-xs" onClick={() => setOpen(false)}>Cancelar</button><button type="button" className="primary-button px-3 py-2 text-xs" disabled={saving || (!entry && !exit)} onClick={save}>{saving ? "Guardando…" : "Confirmar exención"}</button></div></div></div>}</>;
}
